# Usa a mesma imagem base do Python
FROM python:3.10-slim

# Instala as dependências de sistema para áudio
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia e instala as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o resto do projeto
COPY . .

# O comando definitivo que substitui o servidor web pelo operário da fila
CMD ["rq", "worker", "default"]
#toda hora isso